version: '3.9'

services:
  app:
      depends_on:
        - database
      image: wordpress:6.7.1-php8.1-apache
      volumes:
        - ./app:/var/www/html
      ports:
        - '8080:80'
      env_file:
      - .env
      environment:
        WORDPRESS_DB_HOST: database:3306
        WORDPRESS_DB_USER: '${MYSQL_USER}'
        WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
        WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'

  database:
    image: mysql:9.2.0
    ports: 
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

volumes:
  db-data:



    